#!/bin/bash
set -e

# Generated by Project Packager
# Fri Mar 13 13:43:37 GMT 2026

# ============================================
# Project Installation Script
# Generated: 2026-03-13 13:44:01
# Source: wii-covers
# ============================================

# SAFETY CHECK - Only create files, don't execute anything
if [ "$1" != "--extract-only" ]; then
    echo "Usage: $0 --extract-only"
    echo "This script only extracts files, doesn't build or execute them."
    echo "Run with: $0 --extract-only"
    exit 1
fi

echo "📦 Project Packager v1.0"
echo "========================="
echo ""

# Create directory structure
echo "📁 Creating directories..."
mkdir -p "covers"
mkdir -p "covers/2d"
mkdir -p "covers/3d"
echo ""

# Create files
echo "📄 Creating files..."
# LICENSE (1.0 KB)
cat <<EOL > "LICENSE"
MIT License

Copyright (c) 2026 igiteam

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

EOL

# README.md (130 bytes)
cat <<EOL > "README.md"
# wii-covers

wii-covers

python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

EOL

# github-deploy.sh (40 bytes)
cat <<EOL > "github-deploy.sh"
git add .
git commit -m 'fixes'
git push
EOL

# requirements.txt (8 bytes)
cat <<EOL > "requirements.txt"
requests
EOL

# wii-bash.sh (21.8 KB)
cat <<EOL > "wii-bash.sh"
#!/bin/bash

# Wii Covers Complete Automation Script - ENHANCED EDITION
# Run with: curl -o wii-bash.sh https://yourdomain.com/wii-bash.sh && chmod +x wii-bash.sh && sudo ./wii-bash.sh

set -e  # Exit on any error

# ============================================
# Configuration
# ============================================
REPO_URL="https://github.com/igiteam/wii-covers.git"
PROJECT_DIR="\\$HOME/wii-covers"
ZIP_NAME="wii-covers-complete-\\$(date +%Y%m%d-%H%M%S).zip"
PUBLIC_DIR="/var/www/html/wii-covers"
LOG_FILE="/root/wii-deployment-\\$(date +%Y%m%d-%H%M%S).log"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# ============================================
# Helper Functions
# ============================================
log() {
    echo -e "\\${GREEN}[\\$(date '+%Y-%m-%d %H:%M:%S')]\\${NC} \\$1" | tee -a "\\$LOG_FILE"
}

error() {
    echo -e "\\${RED}[ERROR]\\${NC} \\$1" | tee -a "\\$LOG_FILE"
    exit 1
}

warning() {
    echo -e "\\${YELLOW}[WARNING]\\${NC} \\$1" | tee -a "\\$LOG_FILE"
}

section() {
    echo ""
    echo -e "\\${BLUE}═══════════════════════════════════════════════════════════════\\${NC}"
    echo -e "\\${BLUE}  \\$1\\${NC}"
    echo -e "\\${BLUE}═══════════════════════════════════════════════════════════════\\${NC}"
    echo ""
}

check_command() {
    if ! command -v \\$1 &> /dev/null; then
        return 1
    fi
    return 0
}

verify_nginx() {
    if ! systemctl is-active --quiet nginx; then
        log "⚠️ Nginx not running, attempting to start..."
        systemctl start nginx
        sleep 2
        if ! systemctl is-active --quiet nginx; then
            warning "Nginx failed to start, but files are still available locally"
            return 1
        fi
    fi
    return 0
}

# ============================================
# Start Script
# ============================================
clear
echo ""
echo -e "\\${GREEN}╔═══════════════════════════════════════════════════════════════╗\\${NC}"
echo -e "\\${GREEN}║                                                               ║\\${NC}"
echo -e "\\${GREEN}║      Wii Covers Complete Automation Script - ENHANCED        ║\\${NC}"
echo -e "\\${GREEN}║                                                               ║\\${NC}"
echo -e "\\${GREEN}║      This script will:                                        ║\\${NC}"
echo -e "\\${GREEN}║      1. Install all dependencies                              ║\\${NC}"
echo -e "\\${GREEN}║      2. Clone the wii-covers repo                             ║\\${NC}"
echo -e "\\${GREEN}║      3. Download ALL game covers (10,150 games)               ║\\${NC}"
echo -e "\\${GREEN}║      4. Generate HTML website                                 ║\\${NC}"
echo -e "\\${GREEN}║      5. Create ZIP file with everything                       ║\\${NC}"
echo -e "\\${GREEN}║      6. Setup nginx and give you a download URL               ║\\${NC}"
echo -e "\\${GREEN}║                                                               ║\\${NC}"
echo -e "\\${GREEN}╚═══════════════════════════════════════════════════════════════╝\\${NC}"
echo ""

log "Starting deployment at \\$(date)"
log "Log file: \\$LOG_FILE"

# Check if running as root
if [ "\\$EUID" -ne 0 ]; then 
    error "Please run as root (use sudo)"
fi

# ============================================
# Install System Dependencies
# ============================================
section "Installing System Dependencies"

log "Updating package list..."
apt-get update -y

log "Installing required packages..."
apt-get install -y \\
    python3 \\
    python3-pip \\
    python3-venv \\
    git \\
    wget \\
    curl \\
    zip \\
    unzip \\
    nginx \\
    screen \\
    bc \\
    tmux \\
    htop \\
    pv \\
    build-essential \\
    python3-dev \\
    ufw \\
    certbot \\
    python3-certbot-nginx

# Verify nginx installation
if ! check_command nginx; then
    error "Nginx installation failed"
fi
log "✅ Nginx installed successfully"

# Configure firewall
log "Configuring firewall..."
ufw allow 22/tcp comment 'SSH'
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'
echo "y" | ufw enable
log "✅ Firewall configured"

# ============================================
# Clone Repository
# ============================================
section "Cloning Repository"

log "Cleaning up any existing directory..."
rm -rf "\\$PROJECT_DIR"

log "Cloning from \\$REPO_URL..."
git clone "\\$REPO_URL" "\\$PROJECT_DIR"

if [ ! -d "\\$PROJECT_DIR" ]; then
    error "Failed to clone repository"
fi

cd "\\$PROJECT_DIR"
log "✅ Repository cloned successfully"

# ============================================
# Setup Python Environment
# ============================================
section "Setting Up Python Environment"

log "Creating Python virtual environment..."
python3 -m venv venv
source venv/bin/activate

log "Installing Python packages..."
pip install --upgrade pip
pip install requests urllib3 pillow

# Create requirements.txt if it doesn't exist
if [ ! -f "requirements.txt" ]; then
    echo "requests>=2.28.0" > requirements.txt
    echo "urllib3>=1.26.0" >> requirements.txt
fi

pip install -r requirements.txt
log "✅ Python environment ready"

# ============================================
# Check/Create wiitdb.txt
# ============================================
section "Checking Database File"

if [ ! -f "wiitdb.txt" ]; then
    log "wiitdb.txt not found! Creating from sample data..."
    
    # Create a sample with some common games
    cat > wiitdb.txt << 'EOF'
TITLES = https://www.gametdb.com (type: Wii language: ORIG version: 20260307144934)
RSPE01 = New Super Mario Bros. Wii
RZDE01 = The Legend of Zelda: Twilight Princess
RMCE01 = Mario Kart Wii
RSBE01 = Super Smash Bros. Brawl
RZPJ01 = Wii Sports
RSPE02 = Super Mario Galaxy
RZDE02 = Super Mario Galaxy 2
RSPE03 = Donkey Kong Country Returns
RZDE03 = Metroid Prime Trilogy
RSPE04 = Wii Fit Plus
EOF
    log "Created sample wiitdb.txt with 10 games (for testing)"
    warning "For full 10,150 games, upload your real wiitdb.txt to \\$PROJECT_DIR/wiitdb.txt"
else
    GAME_COUNT=\\$(wc -l < wiitdb.txt)
    log "Found wiitdb.txt with \\$GAME_COUNT games"
fi

# ============================================
# Create Directory Structure
# ============================================
log "Creating directory structure..."
mkdir -p covers/{2d,3d}
mkdir -p downloads
mkdir -p logs

# ============================================
# Modify Downloader with Speed Settings
# ============================================
section "Configuring Downloader"

# Check if downloader exists
if [ ! -f "wii-downloader.py" ]; then
    error "wii-downloader.py not found in repository!"
fi

# Ask for speed preference
echo ""
echo "Select download speed (impacts time and ban risk):"
echo "1) 🚀 Fast (0.5s delay) - ~1.5 hours - HIGH RISK OF IP BAN"
echo "2) ⚖️  Balanced (2s delay) - ~6 hours - Recommended"
echo "3) 🐢 Slow (5s delay) - ~14 hours - Safe"
echo "4) 🐌 Ultra slow (10s delay) - ~28 hours - Very safe"
echo ""
read -p "Enter choice (1-4) [default: 2]: " SPEED_CHOICE
SPEED_CHOICE=\\${SPEED_CHOICE:-2}

case \\$SPEED_CHOICE in
    1)
        GAME_DELAY=0.5
        REQUEST_DELAY=0.2
        TOTAL_HOURS=1.5
        warning "FAST MODE: High risk of IP ban!"
        ;;
    2)
        GAME_DELAY=2
        REQUEST_DELAY=0.5
        TOTAL_HOURS=6
        log "Balanced mode: ~6 hours"
        ;;
    3)
        GAME_DELAY=5
        REQUEST_DELAY=1
        TOTAL_HOURS=14
        log "Slow mode: ~14 hours"
        ;;
    4)
        GAME_DELAY=10
        REQUEST_DELAY=2
        TOTAL_HOURS=28
        log "Ultra safe mode: ~28 hours"
        ;;
    *)
        GAME_DELAY=2
        REQUEST_DELAY=0.5
        TOTAL_HOURS=6
        warning "Invalid choice, using balanced mode"
        ;;
esac

# Modify the downloader script
log "Configuring download delays..."
if [ -f "wii-downloader.py" ]; then
    sed -i "s/BETWEEN_GAMES_DELAY = .*/BETWEEN_GAMES_DELAY = \\$GAME_DELAY/g" wii-downloader.py 2>/dev/null || true
    sed -i "s/BETWEEN_REQUESTS_DELAY = .*/BETWEEN_REQUESTS_DELAY = \\$REQUEST_DELAY/g" wii-downloader.py 2>/dev/null || true
    log "✅ Download delays configured"
fi

# Ask for download mode
echo ""
echo "Download mode:"
echo "1) Download only missing covers (recommended)"
echo "2) Download all covers (redownload everything)"
echo "3) Just generate HTML from existing JSON"
read -p "Enter choice (1-3) [default: 1]: " DOWNLOAD_MODE
DOWNLOAD_MODE=\\${DOWNLOAD_MODE:-1}

# ============================================
# Start Download
# ============================================
section "Starting Download Process"

# Create a download script
cat > run_download.sh << 'EOF'
#!/bin/bash
cd "\\$PROJECT_DIR"
source venv/bin/activate
python3 wii-downloader.py
EOF

chmod +x run_download.sh

# Create a tmux session (better than screen)
SESSION_NAME="wii-download"

log "Starting download in tmux session: \\$SESSION_NAME"
log "Estimated time: ~\\${TOTAL_HOURS} hours"

# Kill existing session if any
tmux kill-session -t "\\$SESSION_NAME" 2>/dev/null || true

# Create new session with download command
tmux new-session -d -s "\\$SESSION_NAME" "cd \\$PROJECT_DIR && source venv/bin/activate && python3 wii-downloader.py"

log "✅ Download started in tmux session"
log ""
log "📌 Useful commands:"
log "   - View progress: tmux attach -t \\$SESSION_NAME"
log "   - Detach: Ctrl+B, then D"
log "   - List sessions: tmux ls"
log "   - Kill session: tmux kill-session -t \\$SESSION_NAME"
log ""

# Ask if user wants to attach
echo "Do you want to:"
echo "1) Attach now and watch progress"
echo "2) Detach and let it run (will continue after SSH disconnect)"
echo "3) Exit and check later"
read -p "Enter choice (1-3) [default: 1]: " ATTACH_CHOICE
ATTACH_CHOICE=\\${ATTACH_CHOICE:-1}

if [ "\\$ATTACH_CHOICE" == "1" ]; then
    log "Attaching to tmux session..."
    sleep 2
    tmux attach -t "\\$SESSION_NAME"
fi

# ============================================
# Generate HTML (will run after download)
# ============================================
section "Waiting for Download to Complete"

if [ "\\$ATTACH_CHOICE" != "1" ]; then
    log "Download running in background"
    log "This script will continue once download completes"
    log ""
    
    # Wait for download to finish with timeout check
    while tmux has-session -t "\\$SESSION_NAME" 2>/dev/null; do
        echo -n "."
        sleep 60
    done
    echo ""
    log "Download completed!"
fi

# Verify JSON exists
if [ ! -f "wii_games_covers.json" ]; then
    warning "wii_games_covers.json not found! HTML generation may fail"
fi

log "Generating HTML website..."
if [ -f "wii-html.py" ]; then
    python3 wii-html.py
else
    warning "wii-html.py not found! Creating simple index..."
    cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Wii Covers Collection</title>
    <style>
        body { font-family: Arial; padding: 20px; background: #1a1a1a; color: white; }
        h1 { color: #42991b; }
        .stats { background: #333; padding: 15px; border-radius: 8px; }
    </style>
</head>
<body>
    <h1>🎮 Wii Covers Collection</h1>
    <div class="stats">
        <p>Download completed! Check the covers/ folder.</p>
    </div>
</body>
</html>
EOF
fi

if [ -f "index.html" ]; then
    log "✅ HTML generated successfully"
else
    warning "HTML generation failed"
fi

# ============================================
# Create ZIP Archive
# ============================================
section "Creating ZIP Archive"

log "Creating ZIP archive: \\$ZIP_NAME"

# Check if zip command exists
if ! check_command zip; then
    error "zip command not found!"
fi

# Create ZIP with progress
if check_command pv; then
    zip -r -9 "\\$ZIP_NAME" \\
        covers/ \\
        index.html \\
        wii_games_covers.json \\
        wii_covers_report.html \\
        README.md \\
        wiitdb.txt \\
        -x "*.git*" "venv/*" "__pycache__/*" "*.pyc" 2>/dev/null | pv -l >/dev/null
else
    zip -r -9 "\\$ZIP_NAME" \\
        covers/ \\
        index.html \\
        wii_games_covers.json \\
        wii_covers_report.html \\
        README.md \\
        wiitdb.txt \\
        -x "*.git*" "venv/*" "__pycache__/*" "*.pyc" > /dev/null 2>&1
fi

# Verify ZIP was created
if [ ! -f "\\$ZIP_NAME" ]; then
    error "Failed to create ZIP archive"
fi

# Get file size
ZIP_SIZE=\\$(du -h "\\$ZIP_NAME" | cut -f1)
log "✅ ZIP created: \\$ZIP_NAME (\\$ZIP_SIZE)"

# ============================================
# Setup Web Server
# ============================================
section "Setting Up Web Access"

log "Setting up web directory..."
mkdir -p "\\$PUBLIC_DIR"

# Remove old files
rm -rf "\\$PUBLIC_DIR"/* 2>/dev/null || true

log "Copying files to web directory..."
cp -r covers "\\$PUBLIC_DIR/" 2>/dev/null || warning "No covers folder to copy"
cp index.html "\\$PUBLIC_DIR/" 2>/dev/null || warning "No index.html to copy"
cp wii_games_covers.json "\\$PUBLIC_DIR/" 2>/dev/null || warning "No JSON file to copy"
cp wii_covers_report.html "\\$PUBLIC_DIR/" 2>/dev/null || true
cp "\\$ZIP_NAME" "\\$PUBLIC_DIR/" 2>/dev/null || warning "Failed to copy ZIP"

# Verify files were copied
if [ ! -f "\\$PUBLIC_DIR/index.html" ]; then
    warning "index.html not copied to web directory"
    # Create a simple fallback
    echo "<h1>Wii Covers</h1><p>Download: <a href='\\$ZIP_NAME'>\\$ZIP_NAME</a></p>" > "\\$PUBLIC_DIR/index.html"
fi

# Set permissions
chown -R www-data:www-data "\\$PUBLIC_DIR" 2>/dev/null || true
chmod -R 755 "\\$PUBLIC_DIR"

# Configure nginx (backup existing config)
if [ -f /etc/nginx/sites-available/wii-covers ]; then
    cp /etc/nginx/sites-available/wii-covers /etc/nginx/sites-available/wii-covers.bak
fi

cat > /etc/nginx/sites-available/wii-covers << EOF
server {
    listen 80;
    server_name _;
    
    root \\$PUBLIC_DIR;
    index index.html;
    
    location / {
        try_files \\\\$uri \\\\$uri/ =404;
        autoindex on;
        autoindex_format html;
        autoindex_localtime on;
    }
    
    location ~ \\.zip\\$ {
        add_header Content-Disposition 'attachment; filename="\\$ZIP_NAME"';
        add_header Cache-Control 'no-cache, no-store, must-revalidate';
    }
    
    # Security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/wii-covers /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test nginx configuration
log "Testing nginx configuration..."
if nginx -t; then
    log "✅ Nginx configuration test passed"
    systemctl reload nginx
else
    warning "Nginx configuration test failed, using default config"
    # Restore default
    ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
fi

# Verify nginx is running
if verify_nginx; then
    log "✅ Nginx is running"
else
    warning "Nginx is not running, but files are available locally"
fi

# Get server IP
SERVER_IP=\\$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print \\$1}')

# Test web access locally
log "Testing local web access..."
if curl -s "http://localhost/wii-covers/" | grep -q "html"; then
    log "✅ Web server serving files locally"
else
    warning "Local web test failed, but files are in \\$PUBLIC_DIR"
fi

# ============================================
# Create Status Check Script
# ============================================
cat > /usr/local/bin/check-wii-covers << 'EOF'
#!/bin/bash
PUBLIC_DIR="/var/www/html/wii-covers"
echo "=== Wii Covers Status ==="
echo ""
echo "📊 Files in web directory:"
ls -la \\$PUBLIC_DIR | grep -E "(index|zip|json|covers)" || echo "No files found"
echo ""
echo "🌐 Test URLs:"
echo "   http://localhost/wii-covers/"
echo "   http://\\$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print \\$1}')/wii-covers/"
echo ""
echo "🔍 Nginx status:"
systemctl status nginx --no-pager | grep "Active:"
EOF
chmod +x /usr/local/bin/check-wii-covers

# ============================================
# Final Output
# ============================================
section "DEPLOYMENT COMPLETE!"

echo ""
echo -e "\\${GREEN}═══════════════════════════════════════════════════════════════\\${NC}"
echo -e "\\${GREEN}  YOUR FILES ARE READY!\\${NC}"
echo -e "\\${GREEN}═══════════════════════════════════════════════════════════════\\${NC}"
echo ""
echo -e "\\${YELLOW}📦 DOWNLOAD THE COMPLETE PACKAGE:\\${NC}"
echo -e "\\${BLUE}   http://\\$SERVER_IP/wii-covers/\\$ZIP_NAME\\${NC}"
echo ""
echo -e "\\${YELLOW}🌐 VIEW THE WEBSITE:\\${NC}"
echo -e "\\${BLUE}   http://\\$SERVER_IP/wii-covers/\\${NC}"
echo ""
if [ -f "\\$PROJECT_DIR/wii_games_covers.json" ]; then
    TOTAL_GAMES=\\$(grep -c "cover_url" "\\$PROJECT_DIR/wii_games_covers.json")
    TOTAL_2D=\\$(grep -c "raw.githubusercontent.*2d" "\\$PROJECT_DIR/wii_games_covers.json" 2>/dev/null || echo "unknown")
    echo -e "\\${YELLOW}📊 STATISTICS:\\${NC}"
    echo "   - Total games processed: ~\\$((TOTAL_GAMES / 2))"
    echo "   - 2D covers downloaded: \\$TOTAL_2D"
    echo "   - ZIP size: \\$ZIP_SIZE"
fi
echo "   - Server IP: \\$SERVER_IP"
echo ""
echo -e "\\${YELLOW}📁 FILES LOCATIONS:\\${NC}"
echo "   - Web directory: \\$PUBLIC_DIR"
echo "   - Project directory: \\$PROJECT_DIR"
echo "   - Log file: \\$LOG_FILE"
echo ""
echo -e "\\${YELLOW}🛠️  Management Commands:\\${NC}"
echo "   - Check status: /usr/local/bin/check-wii-covers"
echo "   - View nginx logs: journalctl -u nginx -f"
echo "   - Restart nginx: systemctl restart nginx"
echo "   - View tmux session: tmux attach -t wii-download (if still running)"
echo ""
echo -e "\\${YELLOW}🔧 Troubleshooting:\\${NC}"
echo "   If URLs don't work, check:"
echo "   1. Firewall: ufw status"
echo "   2. Nginx: systemctl status nginx"
echo "   3. Files: ls -la \\$PUBLIC_DIR"
echo ""
echo -e "\\${GREEN}═══════════════════════════════════════════════════════════════\\${NC}"
echo ""

# Save info
cat > /root/wii-covers-info.txt << EOF
Wii Covers Deployment
Date: \\$(date)
ZIP File: http://\\$SERVER_IP/wii-covers/\\$ZIP_NAME
Website: http://\\$SERVER_IP/wii-covers/
Server IP: \\$SERVER_IP
ZIP Size: \\$ZIP_SIZE
Project Dir: \\$PROJECT_DIR
Web Dir: \\$PUBLIC_DIR
Log File: \\$LOG_FILE
EOF

log "✅ All done! Share the download URL above!"
log "ℹ️  Run 'check-wii-covers' anytime to see status"

# cd ~/wii-covers

# # Create wii_games_dolphin.html (copy of index.html)
# cp index.html wii_games_dolphin.html

# # Verify both exist
# ls -la index.html wii_games_dolphin.html

# # Create the complete ZIP archive
# zip -r wii-covers-complete.zip \\
#     index.html \\
#     wii_games_dolphin.html \\
#     wii_games_covers.json \\
#     covers/ \\
#     README.md \\
#     wiitdb.txt \\
#     -x "*.git*" "venv/*" "__pycache__/*" "*.pyc"

# # Check the ZIP
# ls -la wii-covers-complete.zip
# du -sh wii-covers-complete.zip

# # Copy everything to web folder
# cp wii-covers-complete.zip wii_games_dolphin.html /var/www/html/wii-covers/

# # Check web directory
# ls -la /var/www/html/wii-covers/

# IP=\\$(curl -s ifconfig.me)
# echo "http://\\$IP/wii-covers/wii_games_dolphin.html"
# echo "http://\\$IP/wii-covers/wii-covers-complete.zip"

# 🚀 Key Enhancements:
#     ✅ Nginx verification - Checks if installed, tests config, verifies it's running
#     ✅ Firewall setup - Opens ports 80/443 automatically
#     ✅ Better error handling - Graceful fallbacks if files missing
#     ✅ ZIP verification - Confirms ZIP was created successfully
#     ✅ Local web testing - Tests if nginx is serving files
#     ✅ Status check script - check-wii-covers command for later use
#     ✅ Backup configs - Saves backup before overwriting
#     ✅ Better permissions - Ensures www-data owns files
#     ✅ More logging - Every step is logged
#     ✅ Troubleshooting section - Built-in debug tips

# ============================================
# TROUBLESHOOTING COMMANDS - WHAT WE DID
# ============================================

# 🔍 Check if tmux session is still running
# tmux ls
# Output: wii-download: 1 windows (created Thu Mar 12 12:07:33 2026)

# 📊 Attach to see live progress
# tmux attach -t wii-download
# (Shows: [4331/10146] RMCPGP - Mario Kart CTGP Revolution...)
# (To detach: Ctrl+B, then D)

# 📁 Count downloaded covers
# ls -la ~/wii-covers/covers/2d/ | grep -c ".png"
# ls -la ~/wii-covers/covers/3d/ | grep -c ".png"
# Our result: 3954 2D, 3955 3D

# 📄 Check JSON progress
# cat ~/wii-covers/wii_games_covers.json | grep -c "cover_url"
# Our result: 8690 entries (4345 games)

# 🔍 Check if JSON has real covers vs placeholders
# cat ~/wii-covers/wii_games_covers.json | grep -c "raw.githubusercontent"
# Our result: 7909 actual downloaded covers

# 🛑 Check if downloader crashed
# ps aux | grep python | grep wii
# (If nothing shows, download finished or crashed)

# 📝 Check error logs
# ls -la ~/wii-covers/logs/
# cat ~/wii-covers/logs/* 2>/dev/null
# (If empty, no errors logged)

# 💾 Check ZIP creation
# ls -la ~/wii-covers-complete-*.zip
# du -sh ~/wii-covers-complete-*.zip
# Our result: 570M

# 🌐 Check nginx status
# systemctl status nginx
# (Should show: active (running))

# 📂 Check web directory
# ls -la /var/www/html/wii-covers/
# (Should show: index.html, covers/, zip file)

# 🔌 Test web access locally
# curl http://localhost/wii-covers/index.html | head -20
# (Should return HTML)

# 🌍 Get server IP for sharing
# curl ifconfig.me
# Our result: 178.128.40.69

# ✅ Final URLs to share
# echo "http://178.128.40.69/wii-covers/index.html"
# echo "http://178.128.40.69/wii-covers/wii-covers-complete-20250312-182802.zip"
EOL

# wii-downloader.py (15.0 KB)
cat <<EOL > "wii-downloader.py"
#!/usr/bin/env python3
"""
Wii Cover Downloader - Python Edition
Reads a wiitdb.txt file and downloads covers from GameTDB
Organizes covers in 2d/ and 3d/ folders with ID as filename
Saves JSON after EVERY game so you always have up-to-date data
Uses GitHub URLs for all covers (existing or downloaded)
"""

import os
import json
import requests
import re
from pathlib import Path
import time
import random
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Configuration
COVERS_FOLDER = "covers"
JSON_FILE = "wii_games_covers.json"
BACKUP_JSON_FILE = "wii_games_covers_backup.json"
RAW_BASE_URL = "https://raw.githubusercontent.com/igiteam/wii-covers/main/covers"

# Download settings
REQUEST_TIMEOUT = 15  # seconds
MAX_RETRIES = 2
BACKOFF_FACTOR = 1
BETWEEN_REQUESTS_DELAY = 0.2
BETWEEN_GAMES_DELAY = 0.5
MAX_CONSECUTIVE_FAILURES = 5

class WiiCoverDownloader:
    def __init__(self, txt_file):
        self.txt_file = txt_file
        self.games_dict = {}  # Dictionary mapping serial -> title
        self.results = []
        self.session = self._create_session()
        self.consecutive_failures = 0
        self.existing_2d = set()
        self.existing_3d = set()
        
        # Create folder structure
        Path(COVERS_FOLDER).mkdir(parents=True, exist_ok=True)
        Path(os.path.join(COVERS_FOLDER, "2d")).mkdir(parents=True, exist_ok=True)
        Path(os.path.join(COVERS_FOLDER, "3d")).mkdir(parents=True, exist_ok=True)
        
        # Load titles from wiitdb.txt first
        self.load_titles_from_txt()
        
        # Scan for existing covers
        self.scan_existing_covers()
        
        # Try to load existing progress
        self.load_existing_progress()
    
    def load_titles_from_txt(self):
        """Load all game titles from wiitdb.txt into a dictionary"""
        if not os.path.exists(self.txt_file):
            print(f"⚠️  Warning: {self.txt_file} not found!")
            return
        
        print(f"📖 Reading titles from {self.txt_file}...")
        try:
            with open(self.txt_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if '=' in line and not line.startswith('TITLES'):
                        parts = line.split('=', 1)
                        serial = parts[0].strip()
                        title = parts[1].strip()
                        self.games_dict[serial] = title
        except Exception as e:
            print(f"⚠️  Error reading {self.txt_file}: {e}")
        
        print(f"✅ Loaded {len(self.games_dict)} game titles")
    
    def scan_existing_covers(self):
        """Scan for already downloaded cover files"""
        # Scan 2D covers
        if os.path.exists(os.path.join(COVERS_FOLDER, "2d")):
            for file in Path(os.path.join(COVERS_FOLDER, "2d")).glob("*.png"):
                self.existing_2d.add(file.stem)
        
        # Scan 3D covers
        if os.path.exists(os.path.join(COVERS_FOLDER, "3d")):
            for file in Path(os.path.join(COVERS_FOLDER, "3d")).glob("*.png"):
                self.existing_3d.add(file.stem)
        
        print(f"📁 Found {len(self.existing_2d)} existing 2D covers")
        print(f"📁 Found {len(self.existing_3d)} existing 3D covers")
        
    def _create_session(self):
        """Create a requests session with retry strategy"""
        session = requests.Session()
        
        retry_strategy = Retry(
            total=MAX_RETRIES,
            status_forcelist=[429, 500, 502, 503, 504],
            backoff_factor=BACKOFF_FACTOR,
            allowed_methods=["GET"]
        )
        
        adapter = HTTPAdapter(max_retries=retry_strategy, pool_connections=5, pool_maxsize=5)
        session.mount("http://", adapter)
        session.mount("https://", adapter)
        
        session.headers.update({
            'User-Agent': 'WiiCoverDownloader/1.0 (Python)',
            'Accept': 'image/png,image/*;q=0.9,*/*;q=0.8'
        })
        
        return session
    
    def load_existing_progress(self):
        """Load existing JSON file if it exists to resume progress"""
        if os.path.exists(JSON_FILE):
            try:
                with open(JSON_FILE, 'r', encoding='utf-8') as f:
                    self.results = json.load(f)
                print(f"📂 Loaded {len(self.results)} previously processed games from {JSON_FILE}")
            except Exception as e:
                print(f"⚠️  Could not load existing JSON: {e}")
                self.results = []
    
    def save_json(self, is_final=False):
        """Save results to JSON file - called after EVERY game"""
        # Save main JSON
        with open(JSON_FILE, 'w', encoding='utf-8') as f:
            json.dump(self.results, f, indent=2, ensure_ascii=False)
        
        # Also save a backup every 50 games
        if len(self.results) % 50 == 0:
            with open(BACKUP_JSON_FILE, 'w', encoding='utf-8') as f:
                json.dump(self.results, f, indent=2, ensure_ascii=False)
            print(f"  💾 Backup saved: {BACKUP_JSON_FILE}")
        
        # Only show stats on final save or every 100 games
        if is_final or len(self.results) % 100 == 0:
            total = len(self.results)
            with_2d = sum(1 for g in self.results if g['id'] in self.existing_2d)
            with_3d = sum(1 for g in self.results if g['id'] in self.existing_3d)
            
            print(f"\\n📊 Current progress: {total} games processed")
            print(f"   - 2D covers: {with_2d} ({with_2d/total*100:.1f}%)")
            print(f"   - 3D covers: {with_3d} ({with_3d/total*100:.1f}%)")
    
    def is_valid_game_id(self, game_id):
        """Check if the game ID is valid for cover downloading"""
        # System/utility discs often don't have covers
        invalid_patterns = [
            r'^00',  # System discs
            r'^09',  # Channel installers
            r'^41',  # Update discs
            r'^51',  # More system stuff
            r'^52',  # More system stuff
            r'^10',  # Wii Menu
            r'^11',  # System
            r'^1[0-9]',  # Various system tools
        ]
        
        for pattern in invalid_patterns:
            if re.match(pattern, game_id):
                return False
        return True
    
    def download_cover(self, game_id, cover_type):
        """Download a specific cover type for a game"""
        languages = ['EN', 'US', 'JA', 'FR', 'DE', 'ES', 'IT', 'PT', 'NL']
        
        endpoint_map = {
            '2d': 'cover',
            '3d': 'cover3D',
        }
        
        endpoint = endpoint_map.get(cover_type, 'cover')
        folder = cover_type
        
        filename = f"{game_id}.png"
        filepath = os.path.join(COVERS_FOLDER, folder, filename)
        
        # Skip if already downloaded
        if os.path.exists(filepath) and not self.force_redownload:
            self.consecutive_failures = 0
            return True
        
        for lang in languages:
            url = f"https://art.gametdb.com/wii/{endpoint}/{lang}/{game_id}.png"
            
            jitter = random.uniform(0.05, 0.15)
            time.sleep(BETWEEN_REQUESTS_DELAY + jitter)
            
            try:
                response = self.session.get(url, timeout=REQUEST_TIMEOUT, stream=False)
                
                if response.status_code == 200:
                    content_type = response.headers.get('content-type', '')
                    if 'image' in content_type:
                        with open(filepath, 'wb') as f:
                            f.write(response.content)
                        self.consecutive_failures = 0
                        return True
                elif response.status_code == 404:
                    continue
                else:
                    print(f"  ⚠️  Error {response.status_code} for {folder}/{filename} with {lang}")
                    
            except Exception as e:
                print(f"  ⚠️  Error: {e}")
                continue
        
        self.consecutive_failures += 1
        return False
    
    def download_all_covers(self, force_redownload=False):
        """Download all cover types for all games"""
        self.force_redownload = force_redownload
        print(f"\\n🖼️  Downloading covers...")
        print(f"⏱️  JSON will be updated after EVERY game")
        
        # Get list of games to process (from existing covers + potential new ones)
        all_serials = set(self.existing_2d) | set(self.existing_3d) | set(self.games_dict.keys())
        
        # Filter out invalid/system IDs
        valid_serials = [s for s in all_serials if self.is_valid_game_id(s)]
        total_games = len(valid_serials)
        
        print(f"📊 Total unique valid games to process: {total_games}")
        
        start_time = time.time()
        self.consecutive_failures = 0
        
        # Build a set of already processed games from results
        processed_serials = {r['id'] for r in self.results}
        
        for i, game_id in enumerate(sorted(valid_serials), 1):
            # Calculate progress and ETA
            elapsed = time.time() - start_time
            processed = i - 1
            if processed > 0:
                avg_time = elapsed / processed
                remaining = avg_time * (total_games - i + 1)
                eta_min = int(remaining // 60)
                eta_sec = int(remaining % 60)
                eta_str = f" (ETA: {eta_min}m {eta_sec}s)"
            else:
                eta_str = ""
            
            # Check for too many consecutive failures
            if self.consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                print(f"\\n⚠️  Too many failures. Pausing for 10 seconds...")
                time.sleep(10)
                self.consecutive_failures = 0
            
            # Get title from dictionary
            title = self.games_dict.get(game_id, f"Unknown Game ({game_id})")
            
            print(f"\\n[{i}/{total_games}]{eta_str} {game_id} - {title[:50]}...")
            
            # Check if game already exists in results and we're not forcing redownload
            if game_id in processed_serials and not force_redownload:
                print(f"  📝 Already in JSON, skipping...")
                continue
            
            # Create new entry
            game_result = {
                'title': title,
                'id': game_id,
                'cover_url': f"{RAW_BASE_URL}/2d/{game_id}.png",
                '3d_cover_url': f"{RAW_BASE_URL}/3d/{game_id}.png"
            }
            
            # Download missing 2D cover
            if game_id in self.existing_2d:
                print(f"  ✅ 2D cover already exists")
            elif self.download_cover(game_id, '2d'):
                print(f"  ✅ 2D cover downloaded")
                self.existing_2d.add(game_id)
            else:
                print(f"  ⚠️ 2D cover not found")
            
            # Download missing 3D cover
            if game_id in self.existing_3d:
                print(f"  ✅ 3D cover already exists")
            elif self.download_cover(game_id, '3d'):
                print(f"  ✅ 3D cover downloaded")
                self.existing_3d.add(game_id)
            else:
                print(f"  ⚠️ 3D cover not found")
            
            # Add to results
            self.results.append(game_result)
            processed_serials.add(game_id)
            
            # Save JSON after every game
            self.save_json()
            
            # Add delay between games
            if i < total_games:
                time.sleep(BETWEEN_GAMES_DELAY)
        
        # Final save
        self.save_json(is_final=True)
        return self.results

def main():
    print("🎮 Wii Cover Downloader - Python Edition")
    print("=" * 50)
    print("🔄 JSON updates after EVERY game - never lose progress!")
    print("📁 Based on actual cover files in covers/2d/")
    print("📖 Titles from wiitdb.txt")
    print("=" * 50)
    
    # Check for the txt file
    txt_file = "wiitdb.txt"
    if not os.path.exists(txt_file):
        print(f"⚠️  Warning: {txt_file} not found! Titles will be missing.")
    
    # Create downloader instance
    downloader = WiiCoverDownloader(txt_file)
    
    print(f"\\n📊 Statistics:")
    print(f"📁 Existing 2D covers: {len(downloader.existing_2d)}")
    print(f"📁 Existing 3D covers: {len(downloader.existing_3d)}")
    print(f"📖 Titles loaded: {len(downloader.games_dict)}")
    print(f"📂 Already in JSON: {len(downloader.results)}")
    
    # Ask user what to do
    print("\\n📋 What would you like to do?")
    print("1. Download missing covers and update JSON")
    print("2. Download all covers (redownload everything)")
    print("3. Generate JSON from existing covers only (fastest)")
    print("4. Resume interrupted download")
    
    choice = input("\\nEnter your choice (1/2/3/4): ").strip()
    
    if choice == '3':
        # Generate JSON from existing covers only
        print("\\n📝 Generating JSON from existing cover files...")
        
        # Clear results and rebuild from scratch using existing 2D covers
        downloader.results = []
        
        # Use existing 2D covers as the source of truth
        for serial in sorted(downloader.existing_2d):
            # Get title from dictionary
            title = downloader.games_dict.get(serial, f"Unknown Game ({serial})")
            
            game_entry = {
                'title': title,
                'id': serial,
                'cover_url': f"{RAW_BASE_URL}/2d/{serial}.png",
                '3d_cover_url': f"{RAW_BASE_URL}/3d/{serial}.png"
            }
            downloader.results.append(game_entry)
            
            # Save periodically
            if len(downloader.results) % 100 == 0:
                downloader.save_json()
                print(f"  📝 Generated {len(downloader.results)} games...")
        
        downloader.save_json(is_final=True)
        
        # Show stats
        with_3d = len([s for s in downloader.existing_2d if s in downloader.existing_3d])
        print(f"\\n✅ Generated JSON with {len(downloader.results)} games")
        print(f"   - With 2D covers: {len(downloader.existing_2d)}")
        print(f"   - With 3D covers: {with_3d}")
        
    elif choice in ['1', '2', '4']:
        # Download covers
        force = (choice == '2')
        if choice == '4':
            print("📝 Resume mode: Will skip already processed games")
            force = False
        
        downloader.download_all_covers(force_redownload=force)
        
        print(f"\\n✨ All done! Processed {len(downloader.results)} games")
        print(f"\\n📁 Files:")
        print(f"   - Covers: {COVERS_FOLDER}/2d/ and {COVERS_FOLDER}/3d/")
        print(f"   - JSON data: {JSON_FILE}")
        print(f"   - Backup: {BACKUP_JSON_FILE}")
    else:
        print("❌ Invalid choice")

if __name__ == "__main__":
    # Install requests if not available
    try:
        import requests
    except ImportError:
        print("📦 Installing requests...")
        os.system("pip install requests")
        import requests
    
    main()
EOL

# wii-html-v1.py (10.3 KB)
cat <<EOL > "wii-html-v1.py"
#!/usr/bin/env python3
"""
Wii Games Grid Generator
Creates an Xemu-style grid website from your Wii games JSON
Removes duplicates, keeps "Play" status with green background
"""

import json
import os
from datetime import datetime

# Configuration
JSON_FILE = "wii_games_covers.json"
OUTPUT_HTML = "index.html"
PLACEHOLDER_IMAGE = "https://raw.githubusercontent.com/igiteam/wii-covers/main/covers/wii-cover-default.png"
RAW_BASE_URL = "https://raw.githubusercontent.com/igiteam/wii-covers/main/covers"

def load_games_data():
    """Load games from JSON file and remove duplicates by ID"""
    if not os.path.exists(JSON_FILE):
        print(f"❌ Error: {JSON_FILE} not found!")
        print("Please run the cover downloader first to generate the JSON file.")
        return None
    
    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        games = json.load(f)
    
    # Remove duplicates by ID (keep first occurrence)
    seen_ids = set()
    unique_games = []
    for game in games:
        if game['id'] not in seen_ids:
            seen_ids.add(game['id'])
            unique_games.append(game)
    
    if len(unique_games) < len(games):
        print(f"✅ Removed {len(games) - len(unique_games)} duplicates")
    
    print(f"✅ Loaded {len(unique_games)} unique games from {JSON_FILE}")
    return unique_games

def generate_html(games):
    """Generate the grid website HTML matching the exact pattern"""
    
    # Sort games by title for better browsing
    games.sort(key=lambda x: x['title'].lower())
    
    # Stats
    total_games = len(games)
    with_2d = sum(1 for g in games if g['cover_url'] != PLACEHOLDER_IMAGE)
    with_3d = sum(1 for g in games if g['3d_cover_url'] != PLACEHOLDER_IMAGE)
    
    html = f"""<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wii Games Collection</title>

  <link rel="icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" type="image/png">
  <link rel="apple-touch-icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="180x180">
  <link rel="icon" type="image/png" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="192x192">
  <link rel="icon" type="image/png" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="512x512">
  <meta itemprop="name" content="Wii Games Collection">
  <meta property="og:title" content="Wii Games Collection">
  <meta property="og:url" content="">
  <meta property="og:type" content="website">
  <meta name="twitter:title" content="Wii Games Collection">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="apple-touch-icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="180x180">

  <style>
    body {{
      background-color: #1a1a1a;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      margin: 4px 20px;
      padding: 0;
    }}

    #results {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 10px;
      max-width: 1400px;
      margin: 0 auto;
      background-color: #1a1a1a;
      margin-top: 4px;
      z-index: 1000;
    }}

    .title-card {{
      background: #2a2a2a;
      border-radius: 8px;
      overflow: hidden;
      transition: transform 0.2s;
    }}

    .title-card:hover {{
      transform: scale(1.05);
      z-index: 10;
    }}

    .title-card-container {{
      width: 100%;
    }}

    .title-card-image-container {{
      width: 100%;
      aspect-ratio: 3/4;
      overflow: hidden;
    }}

    .title-card-image-container img {{
      width: 100%;
      height: 100%;
      object-fit: cover;
    }}

    .fill-color-Playable {{
      color: #fff !important;
      background-color: #42991b !important;
      font-weight: 700 !important;
    }}

    .card-body {{
      flex: 1 1 auto;
      min-height: 1px;
      padding: 0.5rem 1.25rem !important;
    }}

    .text-center {{
      text-align: center !important;
    }}

    .py-1 {{
      padding-top: 0.25rem !important;
      padding-bottom: 0.25rem !important;
    }}

    .my-0 {{
      margin-top: 0 !important;
      margin-bottom: 0 !important;
    }}

    small {{
      font-size: 80%;
    }}

    a {{
      text-decoration: none;
      color: inherit;
    }}

    /* Search container */
    #saved-search-container {{
      position: sticky;
      top: 0;
      z-index: 10000;
      margin-left: auto;
      margin-right: auto;
      margin: 8px 0px;
      background: #1a1a1a;
      padding: 10px 0;
    }}

    #saved-search-input {{
      padding: 10px;
      width: calc(100% - 20px);
      border: 1px solid #555;
      border-radius: 4px;
      background: #444;
      color: white;
      flex: 1;
    }}

    .search-row {{
      display: flex;
      align-items: center;
      gap: 10px;
    }}

    #saved-search-input::placeholder {{
      color: #aaa;
    }}

    #saved-results-count {{
      color: white;
      font-size: 14px;
      text-align: center;
      margin-top: 5px;
    }}

    .hidden-game {{
      display: none !important;
    }}

    .highlight-saved {{
      border: 3px solid #42991b;
      box-shadow: 0 0 15px #42991b;
    }}
  </style>
</head>

<body>
  <div id="saved-search-container">
    <div class="search-row">
      <img src="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" style="width:34px; border-radius: 4px; background: white; padding: 2px;"
        alt="Wii logo">
      <input type="text" id="saved-search-input" placeholder="Search games...">
      <a href="https://github.com/igiteam/wii-joycon" target="_blank">
        <img src="https://cdn.sdappnet.cloud/rtx/images/wiimote_icon.png" 
             style="width:34px; border-radius: 4px; background: white; padding: 2px;" 
             alt="GitHub">
      </a>
      <a href="https://cdn.sdappnet.cloud/rtx/nintendo-magazine.html" target="_blank">
        <img src="https://cdn.sdappnet.cloud/rtx/images/nintendo-magazine.png" 
             style="width:34px; border-radius: 4px; background: white; padding: 2px;" 
             alt="Nintendo">
      </a>
    </div>
    <div id="saved-results-count"></div>
  </div>

  <div class="row" id="results">
"""

    # Add each game card
    for game in games:
        game_id = game['id']
        title = game['title'].replace('"', '&quot;')
        
        # Determine cover URL
        if game['cover_url'] != PLACEHOLDER_IMAGE:
            cover_url = game['cover_url']
        elif game['3d_cover_url'] != PLACEHOLDER_IMAGE:
            cover_url = game['3d_cover_url']
        else:
            cover_url = PLACEHOLDER_IMAGE
        
        html += f"""
    <div class="col px-1 mb-4 title-card" data-title-name="{title}" data-title-status="Play">
      <a target="_blank" rel="norefferer" href="https://github.com/igiteam/wii-covers">
        <div class="mx-auto title-card-container">

          <div class="title-card-image-container" style="background-position: -3520px -4600px; filter: none;">
            <img
              data-src="{cover_url}"
              class="img-fluid loaded" loading="lazy" title="{title}"
              src="{cover_url}"
              onerror="this.onerror=null; this.src='{PLACEHOLDER_IMAGE}';"
              style="opacity: 1;">
          </div>

          <div class="fill-color-Playable card-body text-center py-1 my-0"><small><strong>Play</strong></small></div>
        </div>
      </a>
    </div>
"""

    html += f"""
  </div>

  <script>
    // Search functionality
    document.getElementById('saved-search-input').addEventListener('input', function (e) {{
      const searchTerm = e.target.value.toLowerCase();
      const cards = document.querySelectorAll('.title-card');
      let count = 0;

      cards.forEach(card => {{
        const title = card.getAttribute('data-title-name') || '';
        if (title.toLowerCase().includes(searchTerm) && searchTerm) {{
          card.classList.remove('hidden-game');
          card.classList.add('highlight-saved');
          count++;
        }} else if (searchTerm) {{
          card.classList.add('hidden-game');
          card.classList.remove('highlight-saved');
        }} else {{
          card.classList.remove('hidden-game');
          card.classList.remove('highlight-saved');
        }}
      }});

      document.getElementById('saved-results-count').textContent =
        searchTerm ? \\`Found \\${{count}} game\\${{count !== 1 ? 's' : ''}}\\` : '';
    }});

    // Keyboard shortcut: / to focus search
    document.addEventListener('keydown', function(e) {{
      if (e.key === '/' && !document.getElementById('saved-search-input').matches(':focus')) {{
        e.preventDefault();
        document.getElementById('saved-search-input').focus();
      }}
    }});
  </script>
</body>

</html>
"""

    return html

def main():
    print("🎮 Wii Games Grid Generator (Xemu Style)")
    print("=" * 50)
    
    # Load games data (duplicates removed)
    games = load_games_data()
    if not games:
        return
    
    # Generate HTML
    print("🔄 Generating grid website...")
    html_content = generate_html(games)
    
    # Save HTML file
    with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✅ Website generated: {OUTPUT_HTML}")
    print(f"\\n📊 Statistics:")
    print(f"   - Total games: {len(games)}")
    print(f"   - With 2D covers: {sum(1 for g in games if g['cover_url'] != PLACEHOLDER_IMAGE)}")
    print(f"   - With 3D covers: {sum(1 for g in games if g['3d_cover_url'] != PLACEHOLDER_IMAGE)}")
    print(f"\\n🌐 Open {OUTPUT_HTML} in your browser to view the grid!")
    print("\\n✨ Features:")
    print("   - Duplicate removal (clean library)")
    print("   - Sticky search bar (press '/' to focus)")
    print("   - Real-time filtering by game name")
    print("   - Hover animations (scale effect)")
    print("   - Green 'Play' status for ALL games")
    print("   - Placeholder image for missing covers")

if __name__ == "__main__":
    main()
  
# Key changes:
#     Removes duplicates by game ID (keeps first occurrence)
#     All games say "Play" with green background (#42991b)
#     Cleaner stats showing unique games
#     Simplified JavaScript (removed unused link wrapping)

# Save this as wii-html.py and run it:
# cd ~/wii-covers
# python3 wii-html.py

# Now you'll have a clean library with no duplicates and proper green "Play" buttons!
EOL

# wii-html.py (14.0 KB)
cat <<EOL > "wii-html.py"
#!/usr/bin/env python3
"""
Wii Games Grid Generator
Creates an Xemu-style grid website from your Wii games JSON
Shows title as text overlay when image fails to load
"""

import json
import os
from datetime import datetime

# Configuration
JSON_FILE = "wii_games_covers.json"
OUTPUT_HTML = "index.html"
PLACEHOLDER_IMAGE = "https://raw.githubusercontent.com/igiteam/wii-covers/main/covers/wii-cover-default.png"
RAW_BASE_URL = "https://raw.githubusercontent.com/igiteam/wii-covers/main/covers"

def load_games_data():
    """Load games from JSON file and remove duplicates by TITLE"""
    if not os.path.exists(JSON_FILE):
        print(f"❌ Error: {JSON_FILE} not found!")
        print("Please run the cover downloader first to generate the JSON file.")
        return None
    
    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        games = json.load(f)
    
    # Debug: Check for Call of Duty
    cod_games = [g for g in games if 'call of duty' in g['title'].lower()]
    if cod_games:
        print(f"🔍 Found {len(cod_games)} Call of Duty games in JSON:")
        for g in cod_games:
            print(f"   - {g['title']}")
    
    # Remove duplicates by TITLE (keep first occurrence)
    seen_titles = set()
    unique_games = []
    for game in games:
        title = game['title'].lower().strip()
        if title not in seen_titles:
            seen_titles.add(title)
            unique_games.append(game)
    
    if len(unique_games) < len(games):
        print(f"✅ Removed {len(games) - len(unique_games)} duplicates by title")
    
    print(f"✅ Loaded {len(unique_games)} unique games from {JSON_FILE}")
    
    # Debug: Check if Call of Duty survived deduplication
    cod_unique = [g for g in unique_games if 'call of duty' in g['title'].lower()]
    if cod_unique:
        print(f"🔍 After deduplication: {len(cod_unique)} Call of Duty games")
        for g in cod_unique:
            print(f"   - {g['title']}")
    
    return unique_games

def generate_html(games):
    """Generate the grid website HTML"""
    
    games.sort(key=lambda x: x['title'].lower())
    
    total_games = len(games)
    with_2d = sum(1 for g in games if g['cover_url'] != PLACEHOLDER_IMAGE)
    with_3d = sum(1 for g in games if g['3d_cover_url'] != PLACEHOLDER_IMAGE)
    
    html = f"""<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wii Games Collection</title>

  <link rel="icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" type="image/png">
  <link rel="apple-touch-icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="180x180">
  <link rel="icon" type="image/png" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="192x192">
  <link rel="icon" type="image/png" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="512x512">
  <meta itemprop="name" content="Wii Games Collection">
  <meta property="og:title" content="Wii Games Collection">
  <meta property="og:url" content="">
  <meta property="og:type" content="website">
  <meta name="twitter:title" content="Wii Games Collection">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="apple-touch-icon" href="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" sizes="180x180">

  <style>
    body {{
      background-color: #1a1a1a;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      margin: 4px 20px;
      padding: 0;
    }}

    #results {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 10px;
      max-width: 1400px;
      margin: 0 auto;
      background-color: #1a1a1a;
      margin-top: 4px;
      z-index: 1000;
    }}

    .title-card {{
      background: #2a2a2a;
      border-radius: 8px;
      overflow: hidden;
      transition: transform 0.2s;
    }}

    .title-card:hover {{
      transform: scale(1.05);
      z-index: 10;
    }}

    .title-card-container {{
      width: 100%;
      position: relative;
    }}

    .title-card-image-container {{
      width: 100%;
      aspect-ratio: 3/4;
      overflow: hidden;
      position: relative;
      background-color: #1a1a1a;
    }}

    .title-card-image-container img {{
      width: 100%;
      height: 100%;
      object-fit: cover;
      transition: opacity 0.3s;
    }}

    /* Style for when image fails to load */
    .title-card-image-container img.error {{
      opacity: 0;
    }}

    .title-card-image-container .fallback-title {{
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 10px;
      box-sizing: border-box;
      background: linear-gradient(135deg, #2a2a2a 0%, #1a1a1a 100%);
      color: #888;
      font-size: 14px;
      font-weight: 500;
      word-break: break-word;
      border: 1px solid #333;
    }}

    .fill-color-Playable {{
      background-color: #42991b !important;
      color: white !important;
      font-weight: 700 !important;
    }}

    .card-body {{
      flex: 1 1 auto;
      min-height: 1px;
      padding: 0.5rem 1.25rem !important;
    }}

    .text-center {{
      text-align: center !important;
    }}

    .py-1 {{
      padding-top: 0.25rem !important;
      padding-bottom: 0.25rem !important;
    }}

    .my-0 {{
      margin-top: 0 !important;
      margin-bottom: 0 !important;
    }}

    small {{
      font-size: 80%;
    }}

    a {{
      text-decoration: none;
      color: inherit;
    }}

    /* Search container */
    #saved-search-container {{
      position: sticky;
      z-index: 10000;
      margin-left: auto;
      margin-right: auto;
      margin: 8px 0px;
    }}

    #saved-search-input {{
      padding: 10px;
      width: calc(100% - 20px);
      border: 1px solid #555;
      border-radius: 4px;
      background: #444;
      color: white;
      flex: 1;
    }}

    .search-row {{
      display: flex;
      align-items: center;
      gap: 10px;
    }}

    .icon {{
      width: 34px;
      height: 34px;
      border-radius: 4px;
      object-fit: cover;
    }}

    #saved-search-input::placeholder {{
      color: #aaa;
    }}

    #saved-results-count {{
      color: white;
      font-size: 14px;
      text-align: center;
      margin-top: 5px;
    }}

    .hidden-game {{
      display: none !important;
    }}

    /* Disable green highlight on search */
    .title-card-link.highlight-saved,
    .highlight-saved {{
      border: none !important;
      box-shadow: none !important;
    }}
  </style>
</head>

<body>
  <div id="saved-search-container">
    <div class="search-row">
      <img src="https://cdn.sdappnet.cloud/rtx/images/dolphin_wii_icon.png" class="icon" alt="Wii logo">
      <input type="text" id="saved-search-input" placeholder="Search games...">
      <a href="https://github.com/igiteam/wiimote" target="_blank">
        <img class="icon" src="https://cdn.sdappnet.cloud/rtx/images/wiimote_icon.png">
      </a>
      <a href="https://cdn.sdappnet.cloud/rtx/nintendo-magazine.html" target="_blank">
        <img class="icon" src="https://cdn.sdappnet.cloud/rtx/images/nintendo-magazine.png">
      </a>
    </div>
    <div id="saved-results-count"></div>
  </div>

  <div class="row" id="results">
"""

    for game in games:
        title = game['title'].replace('"', '&quot;')
        
        if game['cover_url'] != PLACEHOLDER_IMAGE:
            cover_url = game['cover_url']
            has_real_cover = True
        elif game['3d_cover_url'] != PLACEHOLDER_IMAGE:
            cover_url = game['3d_cover_url']
            has_real_cover = True
        else:
            cover_url = PLACEHOLDER_IMAGE
            has_real_cover = False
        
        # If no real cover, show title overlay immediately
        title_display = "flex" if not has_real_cover else "none"
        
        html += f"""
        <div class="col px-1 mb-4 title-card" data-title-name="{title}" data-title-status="Play">
          <a target="_blank" rel="norefferer" href="https://github.com/igiteam/wii-covers">
            <div class="mx-auto title-card-container">
              <div class="title-card-image-container" style="position: relative;">
                <img
                  src="{cover_url}"
                  loading="lazy"
                  title="{title}"
                  onerror="this.classList.add('error'); this.src='{PLACEHOLDER_IMAGE}'; this.parentNode.querySelector('.fallback-title').style.display='flex';">
                <div class="fallback-title" style="display: {title_display}; position: absolute; bottom: 0; left: 0; right: 0; background: linear-gradient(transparent, rgba(0,0,0,0.9)); color: white; padding: 15px 8px 8px 8px; font-size: 12px; text-align: center; font-weight: 500;">{title}</div>
              </div>
              <div class="fill-color-Playable card-body text-center py-1 my-0"><small><strong>Play</strong></small></div>
            </div>
          </a>
        </div>"""

    html += f"""
  </div>

    <script>
      // Convert title cards to links - Wii style!
      function wrapCardsWithLinks() {{
        document.querySelectorAll('.title-card').forEach(card => {{
          const serial = card.getAttribute('data-serial');
          const title = card.getAttribute('data-title-name');
          const status = card.getAttribute('data-title-status');

          // Remove any existing inner link
          const existingInnerLink = card.querySelector('a');
          if (existingInnerLink) {{
            while (existingInnerLink.firstChild) {{
              card.insertBefore(existingInnerLink.firstChild, existingInnerLink);
            }}
            existingInnerLink.remove();
          }}

          // Check if card is already wrapped
          if (card.parentElement?.classList.contains('title-card-link')) {{
            return; // Already wrapped
          }}

          let url_path = '';
          if (title) {{
            url_path = title
              .toLowerCase()
              .replace(/[^\\\\w\\\\s-]/g, '')
              .replace(/\\\\s+/g, '-')
              .replace(/-+/g, '-')
              .replace(/^-|-\\$/g, '');
          }} else if (serial) {{
            url_path = serial;
          }}

          if (url_path) {{
            const urlParams = new URLSearchParams(window.location.search);
            const targetUrl = urlParams.get('url');
            const link = document.createElement('a');

            if (targetUrl) {{
              link.href = targetUrl.replace(/\\\\/\\$/, '') + '/wii/' + url_path;
            }} else {{
              link.href = 'https://meyt.netlify.app/search/' + url_path + ' wii';
            }}

            link.className = 'title-card-link';
            link.rel = 'noopener noreferrer';
            link.target = '_blank';
            link.style.display = 'block';
            link.style.textDecoration = 'none';
            link.style.color = 'inherit';
            
            // Copy data attributes to link for search
            if (title) link.setAttribute('data-title-name', title);
            if (serial) link.setAttribute('data-serial', serial);
            if (status) link.setAttribute('data-title-status', status);

            // Wrap the card with the new link
            card.parentNode.insertBefore(link, card);
            link.appendChild(card);

            const badge = card.querySelector('.fill-color-Playable, .status-badge');
            if (badge && status) {{
              badge.classList.add('status-' + status.toLowerCase());
            }}
          }}
        }});
      }}

      // Run link wrapping
      wrapCardsWithLinks();
      if (document.readyState === 'loading') {{
        document.addEventListener('DOMContentLoaded', wrapCardsWithLinks);
      }} else {{
        wrapCardsWithLinks();
      }}
      setTimeout(wrapCardsWithLinks, 500);

      // Search functionality - NO GREEN BORDERS
      document.getElementById('saved-search-input').addEventListener('input', function (e) {{
        const searchTerm = e.target.value.toLowerCase();
        // Target the title-card-link elements directly
        const links = document.querySelectorAll('.title-card-link');
        let count = 0;

        links.forEach(link => {{
          const title = link.getAttribute('data-title-name') || '';

          if (title.toLowerCase().includes(searchTerm) && searchTerm) {{
            // Show this item
            link.classList.remove('hidden-game');
            // REMOVED: link.classList.add('highlight-saved');
            count++;
          }} else if (searchTerm) {{
            // Hide this item
            link.classList.add('hidden-game');
            // REMOVED: link.classList.remove('highlight-saved');
          }} else {{
            // Show all when search is cleared
            link.classList.remove('hidden-game');
            // REMOVED: link.classList.remove('highlight-saved');
          }}
        }});

        document.getElementById('saved-results-count').textContent =
          searchTerm ? \\`Found \\${{count}} game\\${{count !== 1 ? 's' : ''}}\\` : '';
      }});

      // Keyboard shortcut
      document.addEventListener('keydown', function(e) {{
        if (e.key === '/' && !document.getElementById('saved-search-input').matches(':focus')) {{
          e.preventDefault();
          document.getElementById('saved-search-input').focus();
        }}
      }});
  </script>
</body>

</html>
"""

    return html

def main():
    print("🎮 Wii Games Grid Generator (Xemu Style)")
    print("=" * 50)
    
    games = load_games_data()
    if not games:
        return
    
    print("🔄 Generating grid website...")
    html_content = generate_html(games)
    
    with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✅ Website generated: {OUTPUT_HTML}")
    print(f"\\n📊 Statistics:")
    print(f"   - Total games: {len(games)}")
    print(f"   - With 2D covers: {sum(1 for g in games if g['cover_url'] != PLACEHOLDER_IMAGE)}")
    print(f"   - With 3D covers: {sum(1 for g in games if g['3d_cover_url'] != PLACEHOLDER_IMAGE)}")

if __name__ == "__main__":
    main()
EOL

# wii-packaging.sh (3.5 KB)
cat <<EOL > "wii-packaging.sh"
#!/bin/bash

# Wii Covers - Final Packaging Script
# Run this to regenerate HTML, create dolphin copy, and final ZIP

set -e

# Colors - FIXED
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

echo -e "\\${GREEN}📦 Wii Covers - Final Packaging\\${NC}"
echo "=================================="
echo ""

# Create web directory if it doesn't exist
echo -e "\\${YELLOW}📁 Ensuring web directory exists...\\${NC}"
sudo mkdir -p /var/www/html/wii-covers/
sudo chmod 755 /var/www/html/wii-covers/

cd ~/wii-covers

# STEP 0: REDOWNLOAD THE LATEST wii-downloader.py
echo -e "\\${YELLOW}⬇️ Downloading latest wii-downloader.py from GitHub...\\${NC}"
mv wii-downloader.py wii-downloader.py.bak 2>/dev/null || true
wget -O wii-downloader.py https://raw.githubusercontent.com/igiteam/wii-covers/refs/heads/main/wii-downloader.py
chmod +x wii-downloader.py
echo -e "\\${BLUE}✅ wii-html.py updated\\${NC}"
echo ""

# STEP 0: REDOWNLOAD THE LATEST wii-html.py
echo -e "\\${YELLOW}⬇️ Downloading latest wii-html.py from GitHub...\\${NC}"
mv wii-html.py wii-html.py.bak 2>/dev/null || true
wget -O wii-html.py https://raw.githubusercontent.com/igiteam/wii-covers/refs/heads/main/wii-html.py
chmod +x wii-html.py
echo -e "\\${BLUE}✅ wii-html.py updated\\${NC}"
echo ""

# STEP 1: REGENERATE HTML FROM LATEST JSON
echo -e "\\${YELLOW}🔄 Regenerating index.html from latest data...\\${NC}"
python3 wii-html.py

# STEP 2: Create dolphin HTML file (copy of fresh index)
echo -e "\\${YELLOW}📄 Creating wii_games_dolphin.html...\\${NC}"
cp index.html wii_games_dolphin.html

# STEP 3: Verify both exist
echo -e "\\${BLUE}✅ Files present:\\${NC}"
ls -la index.html wii_games_dolphin.html wii_games_covers.json
echo ""

# STEP 4: Create the complete ZIP archive
echo -e "\\${YELLOW}📦 Creating ZIP archive...\\${NC}"
zip -r wii-covers-complete.zip \\
    index.html \\
    wii_games_dolphin.html \\
    wii_games_covers.json \\
    covers/ \\
    README.md \\
    wiitdb.txt \\
    -x "*.git*" "venv/*" "__pycache__/*" "*.pyc"

# STEP 5: Check the ZIP
echo -e "\\${BLUE}✅ ZIP created:\\${NC}"
ls -la wii-covers-complete.zip
ZIP_SIZE=\\$(du -sh wii-covers-complete.zip | cut -f1)
echo "Size: \\$ZIP_SIZE"
echo ""

# STEP 6: Copy everything to web folder
echo -e "\\${YELLOW}🌐 Copying to web directory...\\${NC}"
sudo cp wii-covers-complete.zip wii_games_dolphin.html /var/www/html/wii-covers/

# Also copy the fresh index and JSON
sudo cp index.html wii_games_covers.json /var/www/html/wii-covers/

# STEP 7: Check web directory
echo -e "\\${BLUE}✅ Web directory contents:\\${NC}"
ls -la /var/www/html/wii-covers/
echo ""

# STEP 8: Get IP and show download links
IP=\\$(curl -s ifconfig.me)
echo -e "\\${GREEN}═══════════════════════════════════════════════════════════════\\${NC}"
echo -e "\\${GREEN}  DOWNLOAD LINKS READY!\\${NC}"
echo -e "\\${GREEN}═══════════════════════════════════════════════════════════════\\${NC}"
echo ""
echo -e "\\${YELLOW}🌐 Main Website:\\${NC}"
echo "   http://\\$IP/wii-covers/index.html"
echo ""
echo -e "\\${YELLOW}🌐 Dolphin HTML:\\${NC}"
echo "   http://\\$IP/wii-covers/wii_games_dolphin.html"
echo ""
echo -e "\\${YELLOW}📦 Complete ZIP:\\${NC}"
echo "   http://\\$IP/wii-covers/wii-covers-complete.zip"
echo ""
echo -e "\\${YELLOW}📊 JSON Data:\\${NC}"
echo "   http://\\$IP/wii-covers/wii_games_covers.json"
echo ""
echo -e "\\${GREEN}✅ Done!\\${NC}"
EOL

# wiitdb.txt (351.4 KB)
cat <<EOL > "wiitdb.txt"
TITLES = https://www.gametdb.com (type: Wii language: ORIG version: 20260307144934)
007E01 = Auto Erase Disc
091E00 = Movie-Ch Install Disc Ver. A


EOL

echo "  Processed 10/10 files..."
echo ""
# Display statistics
echo "✅ Project successfully recreated!"
echo "📊 Statistics:"
echo "   • Directories: 3"
echo "   • Files: 10"
echo "   • Skipped: 7915"
echo "   • Total size: 0.4 MB"
echo "🏠 Location: $(pwd)"
echo "🚀 Ready to use!"

# End of script

echo "File List"
echo "========="
echo ""
echo "[FOLDER] covers/"
echo "[FOLDER] covers/3d/"
echo "[FOLDER] covers/2d/"
echo "[PY    ] wii-html.py (14.01 KiB)"
echo "[SH    ] github-deploy.sh (40.0 B)"
echo "[FILE  ] LICENSE (1.04 KiB)"
echo "[TXT   ] requirements.txt (8.0 B)"
echo "[PY    ] wii-downloader.py (15.01 KiB)"
echo "[MD    ] README.md (130.0 B)"
echo "[SH    ] wii-bash.sh (21.77 KiB)"
echo "[SH    ] wii-packaging.sh (3.49 KiB)"
echo "[PY    ] wii-html-v1.py (10.29 KiB)"
echo "[TXT   ] wiitdb.txt (351.35 KiB)"
echo ""
echo "End of File List"